// Generated by CoffeeScript 1.4.0
"use strict";

var PageCtrl, app;

app = angular.module('flow', ['ui']);

app.config(function($interpolateProvider) {
  $interpolateProvider.startSymbol('{[');
  return $interpolateProvider.endSymbol(']}');
});

app.run(['$rootScope', function($rootScope) {}]);

PageCtrl = (function() {

  function PageCtrl($scope, $rootScope, $http) {
    $scope.loading = true;
    $scope.url = document.location.pathname;
    $http.get($scope.url).success(function(data, status, headers, config) {
      $scope.loading = false;
      $rootScope.$broadcast('loadComplete');
      $scope.chapter = new Chapter(data.chapter);
      $scope.series = new Series(data.series);
      $scope.pages = new PageList(data.pages);
      return $scope.page = data.pages.getCurrent();
    });
  }

  return PageCtrl;

})();
