Flow\Entities\Series:
  type: entity
  table: series
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      unique: true
  oneToMany:
    chapters:
      targetEntity: Chapter
      mappedBy: series