Flow\Entities\Page:
  type: entity
  table: page
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    filename:
      type: string
    page_no:
      type: integer
    height:
      type: integer
      nullable: true
    width:
      type: integer
      nullable: true
  manyToOne:
    chapter:
      targetEntity: Chapter
      inversedBy: pages
  uniqueConstraints:
    page_number_idx:
      columns: chapter_id, page_no